<wsdl:definitions targetNamespace="https://www.supernotariado.gov.co/services/bachue/ee/RRRMatriculas/v1"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:bachue="https://www.supernotariado.gov.co/services/bachue/ee/RRRMatriculas/v1"
                  xmlns:bachue5="https://www.supernotariado.gov.co/schemas/bachue/ee/RRRMatriculas/consultarRRRMatriculas/v1"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="https://www.supernotariado.gov.co/schemas/bachue/ee/RRRMatriculas/consultarRRRMatriculas/v1"
              schemaLocation="../Schemas/Legacy/EE_CC_ConsultarRRRMatriculas.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="ConsultarRRRMatriculas_Request">
    <wsdl:part name="entrada" element="bachue5:entradaConsultarRRRMatriculas"/>
  </wsdl:message>
  <wsdl:message name="ConsultarRRRMatriculas_Response">
    <wsdl:part name="salida" element="bachue5:salidaConsultarRRRMatriculas"/>
  </wsdl:message>
  <wsdl:portType name="BS_SBB_CB_RRRMatriculas">
    <wsdl:operation name="ConsultarRRRMatriculas">
      <wsdl:input message="bachue:ConsultarRRRMatriculas_Request"/>
      <wsdl:output message="bachue:ConsultarRRRMatriculas_Response"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BS_SBB_CB_RRRMatriculas" type="bachue:BS_SBB_CB_RRRMatriculas">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ConsultarRRRMatriculas">
      <soap12:operation style="document"
                        soapAction="https://www.supernotariado.gov.co/services/bachue/ee/RRRMatriculas/v1/ConsultarRRRMatriculas"/>
      <wsdl:input>
        <soap12:body use="literal" parts="entrada"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="salida"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BS_SBB_CB_RRRMatriculas">
    <wsdl:port name="BS_SBB_CB_RRRMatriculasPort" binding="bachue:BS_SBB_CB_RRRMatriculas">
      <soap12:address location="http://www.example.com"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>