<wsdl:definitions targetNamespace="https://www.supernotariado.gov.co/services/bachue/ee/nuevasMatriculas/v1"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:bachue="https://www.supernotariado.gov.co/services/bachue/ee/nuevasMatriculas/v1"
                  xmlns:bachue5="https://www.supernotariado.gov.co/schemas/bachue/ee/nuevasMatriculas/consultarNuevasMatriculas/v1"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="https://www.supernotariado.gov.co/schemas/bachue/ee/nuevasMatriculas/consultarNuevasMatriculas/v1"
              schemaLocation="../Schemas/Legacy/EE_CC_ConsultarNuevasMatriculas.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="ConsultarNuevasMatriculas_Request">
    <wsdl:part name="entrada" element="bachue5:entradaConsultarNuevasMatriculas"/>
  </wsdl:message>
  <wsdl:message name="ConsultarNuevasMatriculas_Response">
    <wsdl:part name="salida" element="bachue5:salidaConsultarNuevasMatriculas"/>
  </wsdl:message>
  <wsdl:portType name="SBB_EE_NuevasMatriculas">
    <wsdl:operation name="ConsultarNuevasMatriculas">
      <wsdl:input message="bachue:ConsultarNuevasMatriculas_Request"/>
      <wsdl:output message="bachue:ConsultarNuevasMatriculas_Response"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SBB_EE_NuevasMatriculas" type="bachue:SBB_EE_NuevasMatriculas">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ConsultarNuevasMatriculas">
      <soap12:operation style="document"
                        soapAction="https://www.supernotariado.gov.co/services/bachue/ee/NuevasMatriculas/v1/ConsultarNuevasMatriculas"/>
      <wsdl:input>
        <soap12:body use="literal" parts="entrada"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="salida"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SBB_EE_NuevasMatriculas">
    <wsdl:port name="SBB_EE_NuevasMatriculasPort" binding="bachue:SBB_EE_NuevasMatriculas">
      <soap12:address location="http://www.example.com"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>