<wsdl:definitions targetNamespace="https://www.supernotariado.gov.co/services/bachue/ee/indicePropietarios/v1"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:bachue="https://www.supernotariado.gov.co/services/bachue/ee/indicePropietarios/v1"
                  xmlns:bachue2="https://www.supernotariado.gov.co/services/bachue/ee/indicepropietarios/consultar/v1"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="https://www.supernotariado.gov.co/services/bachue/ee/indicepropietarios/consultar/v1"
              schemaLocation="../Schemas/EE_IP_consultar.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="Consultar_Request">
    <wsdl:part name="entrada" element="bachue2:entradaIndicePropietarios"/>
  </wsdl:message>
  <wsdl:message name="Consultar_Response">
    <wsdl:part name="salida" element="bachue2:salidaIndicePropietarios"/>
  </wsdl:message>
  <wsdl:portType name="SBB_EE_IndicePropietarios">
    <wsdl:operation name="consultar">
      <wsdl:input message="bachue:Consultar_Request"/>
      <wsdl:output message="bachue:Consultar_Response"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SBB_EE_IndicePropietarios" type="bachue:SBB_EE_IndicePropietarios">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultar">
      <soap12:operation style="document"
                        soapAction="https://www.supernotariado.gov.co/services/bachue/cb/indicepropietarios/consultar/v1"/>
      <wsdl:input>
        <soap12:body use="literal" parts="entrada"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="salida"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SBB_EE_IndicePropietarios">
    <wsdl:port name="SBB_EE_IndicePropietariosPort" binding="bachue:SBB_EE_IndicePropietarios">
      <soap12:address location="http://www.example.com"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>