<wsdl:definitions targetNamespace="https://www.supernotariado.gov.co/services/bachue/ci/licenciasCuradurias/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:bachue="https://www.supernotariado.gov.co/services/bachue/ci/licenciasCuradurias/v1" xmlns:bachue1="https://www.supernotariado.gov.co/schemas/bachue/ci/licenciasCuradurias/consultarLicenciasPorMatricula/v1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="https://www.supernotariado.gov.co/schemas/bachue/ci/licenciasCuradurias/consultarLicenciasPorMatricula/v1" schemaLocation="../Schemas/Legacy/CI_CC_ConsultarLicenciasPorMatricula.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarLicenciasPorMatricula_Request">
        <wsdl:part name="entrada" element="bachue1:entradaConsultarLicenciasPorMatricula"/>
    </wsdl:message>
    <wsdl:message name="ConsultarLicenciasPorMatricula_Response">
        <wsdl:part name="salida" element="bachue1:salidaConsultarLicenciasPorMatricula"/>
    </wsdl:message>
    <wsdl:portType name="SBB_CI_LicenciasCuradurias">
        <wsdl:operation name="ConsultarLicenciasPorMatricula">
            <wsdl:input message="bachue:ConsultarLicenciasPorMatricula_Request"/>
            <wsdl:output message="bachue:ConsultarLicenciasPorMatricula_Response"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="SBB_CI_LicenciasCuradurias" type="bachue:SBB_CI_LicenciasCuradurias">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="ConsultarLicenciasPorMatricula">
            <soap12:operation style="document" soapAction="https://www.supernotariado.gov.co/services/bachue/ci/LicenciasCuradurias/v1/ConsultarLicenciasPorMatricula" soapActionRequired="false"/>
            <wsdl:input>
                <soap12:body use="literal" parts="entrada"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" parts="salida"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="SBB_CI_LicenciasCuradurias">
        <wsdl:port name="SBB_CI_LicenciasCuraduriasPort" binding="bachue:SBB_CI_LicenciasCuradurias">
            <soap12:address location="http://www.example.com"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>