<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:bachue="https://www.supernotariado.gov.co/services/bachue/cn/notificadorcorrespondencia/v1"
  targetNamespace="https://www.supernotariado.gov.co/services/bachue/cn/notificadorcorrespondencia/v1"
  xmlns:bachue1="https://www.supernotariado.gov.co/schemas/bachue/cn/notificadorcorrespondencia/notificarcorrespondencia/v1"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="https://www.supernotariado.gov.co/schemas/bachue/cn/notificadorcorrespondencia/notificarcorrespondencia/v1" schemaLocation="../Schemas/Legacy/CN_NC_NotificarCorrespondencia.xsd" />
		</schema>
	</wsdl:types>

	<wsdl:message name="NotificarCorrespondencia_Request">
		<wsdl:part name="entrada" element="bachue1:entradaNotificarCorrespondencia"/>
	</wsdl:message>
	<wsdl:message name="NotificarCorrespondencia_Response">
		<wsdl:part name="salida" element="bachue1:salidaNotificarCorrespondencia"/>
	</wsdl:message>
	
	<wsdl:portType name="SUT_CN_NotificadorCorrespondencia">
		<wsdl:operation name="NotificarCorrespondencia">
			<wsdl:input message="bachue:NotificarCorrespondencia_Request"/>
			<wsdl:output message="bachue:NotificarCorrespondencia_Response"/>
		</wsdl:operation>
	</wsdl:portType>
 <wsdl:binding name="SUT_CN_NotificadorCorrespondencia" type="bachue:SUT_CN_NotificadorCorrespondencia">
  <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  <wsdl:operation name="NotificarCorrespondencia">
   <soap12:operation style="document"
                     soapAction="https://www.supernotariado.gov.co/services/bachue/cn/notificadorcorrespondencia/v1/NotificarCorrespondencia"/>
   <wsdl:input>
    <soap12:body use="literal" parts="entrada"/>
   </wsdl:input>
   <wsdl:output>
    <soap12:body use="literal" parts="salida"/>
   </wsdl:output>
  </wsdl:operation>
 </wsdl:binding>
 <wsdl:service name="SUT_CN_NotificadorCorrespondencia">
  <wsdl:port name="SUT_CN_NotificadorCorrespondenciaPort" binding="bachue:SUT_CN_NotificadorCorrespondencia">
   <soap12:address location="http://www.example.com"/>
  </wsdl:port>
 </wsdl:service>
</wsdl:definitions>