<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:bachue="https://www.supernotariado.gov.co/services/bachue/ee/cambiopropietario/v1"
  targetNamespace="https://www.supernotariado.gov.co/services/bachue/ee/cambiopropietario/v1"
  xmlns:bachue1="https://www.supernotariado.gov.co/schemas/bachue/ee/cambioPropietario/consultarCambioPropietario/v1"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="https://www.supernotariado.gov.co/schemas/bachue/ee/cambioPropietario/consultarCambioPropietario/v1"
           schemaLocation="../Schemas/Legacy/EE_CC_ConsultarCambioPropietario.xsd" />
		</schema>
	</wsdl:types>

	<wsdl:message name="ConsultarCambioPropietario_Request">
		<wsdl:part name="entrada" element="bachue1:entradaConsultarCambioPropietario"/>
	</wsdl:message>
	<wsdl:message name="ConsultarCambioPropietario_Response">
		<wsdl:part name="salida" element="bachue1:salidaConsultarCambioPropietario"/>
	</wsdl:message>

	<wsdl:portType name="BS_SBB_CB_CambioPropietario">
		<wsdl:operation name="ConsultarCambioPropietario">
			<wsdl:input message="bachue:ConsultarCambioPropietario_Request"/>
			<wsdl:output message="bachue:ConsultarCambioPropietario_Response"/>
		</wsdl:operation>
	</wsdl:portType>
 <wsdl:binding name="BS_SBB_CB_CambioPropietario" type="bachue:BS_SBB_CB_CambioPropietario">
  <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  <wsdl:operation name="ConsultarCambioPropietario">
   <soap12:operation style="document"
                     soapAction="https://www.supernotariado.gov.co/schemas/bachue/ee/cambioPropietario/v1/consultarCambioPropietario"/>
   <wsdl:input>
    <soap12:body use="literal" parts="entrada"/>
   </wsdl:input>
   <wsdl:output>
    <soap12:body use="literal" parts="salida"/>
   </wsdl:output>
  </wsdl:operation>
 </wsdl:binding>
 <wsdl:service name="BS_SBB_CB_CambioPropietario">
  <wsdl:port name="BS_SBB_CB_CambioPropietarioPort" binding="bachue:BS_SBB_CB_CambioPropietario">
   <soap12:address location="http://www.example.com"/>
  </wsdl:port>
 </wsdl:service>
</wsdl:definitions>