<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:bachue="https://www.supernotariado.gov.co/services/bachue/cr/enviocorrespondenciafisica/v1"
  targetNamespace="https://www.supernotariado.gov.co/services/bachue/cr/enviocorrespondenciafisica/v1"
  xmlns:bachue1="https://www.supernotariado.gov.co/schemas/bachue/cr/enviocorrespondenciafisica/enviarcorrespondenciafisica/v1"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="https://www.supernotariado.gov.co/schemas/bachue/cr/enviocorrespondenciafisica/enviarcorrespondenciafisica/v1" schemaLocation="../Schemas/Legacy/CR_ECF_EnviarCorrespondenciaFisica.xsd" />
		</schema>
	</wsdl:types>

	<wsdl:message name="EnviarCorrespondenciaFisica_Request">
		<wsdl:part name="entrada" element="bachue1:entradaEnviarCorrespondenciaFisica"/>
	</wsdl:message>
	<wsdl:message name="EnviarCorrespondenciaFisica_Response">
		<wsdl:part name="salida" element="bachue1:salidaEnviarCorrespondenciaFisica"/>
	</wsdl:message>
	
	<wsdl:portType name="SUT_CR_EnvioCorrespondenciaFisica">
		<wsdl:operation name="EnviarCorrespondenciaFisica">
			<wsdl:input message="bachue:EnviarCorrespondenciaFisica_Request"/>
			<wsdl:output message="bachue:EnviarCorrespondenciaFisica_Response"/>
		</wsdl:operation>
	</wsdl:portType>
 <wsdl:binding name="SUT_CR_EnvioCorrespondenciaFisicaSOAP12Binding" type="bachue:SUT_CR_EnvioCorrespondenciaFisica">
  <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  <wsdl:operation name="EnviarCorrespondenciaFisica">
   <soap12:operation style="document"
                     soapAction="https://www.supernotariado.gov.co/services/bachue/cr/enviocorrespondenciafisica/v1/EnviarCorrespondenciaFisica"/>
   <wsdl:input>
    <soap12:body use="literal" parts="entrada"/>
   </wsdl:input>
   <wsdl:output>
    <soap12:body use="literal" parts="salida"/>
   </wsdl:output>
  </wsdl:operation>
 </wsdl:binding>
 <wsdl:service name="SUT_CR_EnvioCorrespondenciaFisica">
  <wsdl:port name="SUT_CR_EnvioCorrespondenciaFisicaPort" binding="bachue:SUT_CR_EnvioCorrespondenciaFisicaSOAP12Binding">
   <soap12:address location="http://www.example.com"/>
  </wsdl:port>
 </wsdl:service>
</wsdl:definitions>