<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:bachue="https://www.supernotariado.gov.co/services/bachue/cb/anotaciones/v1"
                  targetNamespace="https://www.supernotariado.gov.co/services/bachue/cb/anotaciones/v1"
                  xmlns:bachue4="https://www.supernotariado.gov.co/services/bachue/cb/anotaciones/consultarAnotaciones/v1"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="https://www.supernotariado.gov.co/services/bachue/cb/anotaciones/consultarAnotaciones/v1"
              schemaLocation="../Schemas/Legacy/CB_A_consultarAnotaciones.xsd"/>
    </schema>
  </wsdl:types>
  <!-- INICIO WSDL:mesage -->
  <wsdl:message name="ConsultarAnotaciones_Request">
    <wsdl:part name="entrada" element="bachue4:entradaDatosAnotacion"></wsdl:part>
  </wsdl:message>
  <wsdl:message name="ConsultarAnotaciones_Response">
    <wsdl:part name="salida" element="bachue4:salidaDatosAnotacion"></wsdl:part>
  </wsdl:message>
  <!-- INICIO WSDL:portType -->
  <wsdl:portType name="SBB_CB_Anotaciones">
    <!-- Inicio Operacion consultarAnotaciones -->
    <wsdl:operation name="consultarAnotaciones">
      <wsdl:input message="bachue:ConsultarAnotaciones_Request"></wsdl:input>
      <wsdl:output message="bachue:ConsultarAnotaciones_Response"></wsdl:output>
    </wsdl:operation>
    <!-- Fin Operacion consultarAnotaciones -->
  </wsdl:portType>
  <!-- INICIO WSDL:binding -->
  <wsdl:binding name="SBB_CB_AnotacionesSOAP12Binding" type="bachue:SBB_CB_Anotaciones">
    <!-- Inicio Binding DatosInmueble -->
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultarAnotaciones">
      <soap12:operation style="document"
                        soapAction="https://www.supernotariado.gov.co/services/bachue/cb/operacionesAnotaciones/v1/consultarAnotaciones"/>
      <wsdl:input>
        <soap12:body use="literal" parts="entrada"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="salida"/>
      </wsdl:output>
    </wsdl:operation>
    <!-- Fin Binding DatosInmueble -->
  </wsdl:binding>
  <wsdl:service name="SBB_CB_Anotaciones">
    <wsdl:port name="SBB_CB_AnotacionesPort" binding="bachue:SBB_CB_AnotacionesSOAP12Binding">
      <soap12:address location="http://www.example.com"/>
    </wsdl:port>
  </wsdl:service>
  <!-- Últimas modificaciones 2020-01-27 11:13 -->
</wsdl:definitions>