<wsdl:definitions name="escribirJmsNPRegLiquidacion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/BachueOSB/ExpuestosFinancieras/escribirJmsNPRegLiquidacion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/BachueOSB/ExpuestosFinancieras/escribirJmsNPRegLiquidacion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:imp1="https://www.supernotariado.gov.co/schemas/bachue/np/operacionesfinancieras/registrarliquidacion/v2" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="Produce_MessageNPRegLiquidacion_plt">
    <plt:role name="Produce_MessageNPRegLiquidacion_role">
      <plt:portType name="tns:Produce_MessageNPRegLiquidacion_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="https://www.supernotariado.gov.co/schemas/bachue/np/operacionesfinancieras/registrarliquidacion/v2" schemaLocation="../Schemas/Legacy/NP_OF_RegistrarLiquidacion.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="Produce_MessageNPRegLiquidacion_msg">
        <wsdl:part name="body" element="imp1:entradaRegistrarLiquidacion"/>
    </wsdl:message>
    <wsdl:portType name="Produce_MessageNPRegLiquidacion_ptt">
        <wsdl:operation name="Produce_MessageNPRegLiquidacion">
            <wsdl:input message="tns:Produce_MessageNPRegLiquidacion_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>