<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Bachue/ExpuestosFinancieras/PS_LeerJmsNPRegLiq" name="PS_LeerJmsNPRegLiq-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="PS_LeerJmsNPRegLiq.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Bachue/ExpuestosFinancieras/PS_LeerJmsNPRegLiq"/>
    <wsdl:binding name="ConsumirJms_NPRegLiq_ptt-binding" type="ps:ConsumirJms_NPRegLiq_ptt" xmlns:ps="http://xmlns.oracle.com/pcbpel/adapter/jms/Bachue/ExpuestosFinancieras/PS_LeerJmsNPRegLiq">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsumirJms_NPRegLiq">
            <soap:operation soapAction="ConsumirJms_NPRegLiq"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>