<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Bachue/ExpuestosFinancieras/PS_LeerJmsCBRegPago" name="PS_LeerJmsCBRegPago-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="PS_LeerJmsCBRegPago.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Bachue/ExpuestosFinancieras/PS_LeerJmsCBRegPago"/>
    <wsdl:binding name="ConsumirJms_CBRegPago_ptt-binding" type="ps:ConsumirJms_CBRegPago_ptt" xmlns:ps="http://xmlns.oracle.com/pcbpel/adapter/jms/Bachue/ExpuestosFinancieras/PS_LeerJmsCBRegPago">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsumirJms_CBRegPago">
            <soap:operation soapAction="ConsumirJms_CBRegPago"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>