<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/BachueOSB/Comunes/RegistroJmsAuditoria" name="RegistroJmsAuditoria-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="RegistroJmsAuditoria.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/BachueOSB/Comunes/RegistroJmsAuditoria"/>
    <wsdl:binding name="ProducirJmsAuditoria_ptt-binding" type="reg:ProducirJmsAuditoria_ptt" xmlns:reg="http://xmlns.oracle.com/pcbpel/adapter/jms/BachueOSB/Comunes/RegistroJmsAuditoria">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ProducirJmsAuditoria">
            <soap:operation soapAction="ProducirJmsAuditoria"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>